/** 操作日志 · 资源类型中文映射（与后端 operationlog Resource 一致） */
export const OPERATION_LOG_RESOURCE_LABEL: Record<string, string> = {
  auth: '认证',
  tenant: '租户',
  settings: '系统设置',
  product: '商品',
  product_sku: '商品规格',
  product_publication_sku: '刊登 SKU',
  product_publish_task: '商品刊登任务',
  product_publication: '商品刊登记录',
  image_task: 'AI 图片任务',
  ai_image_task_item: 'AI 图片任务项',
  ai_operation_batch: 'AI 批量任务',
  collect_task: '采集任务',
  collect_batch: '采集批次',
  collect_rule: '采集规则',
  collect_browser_profile: '采集浏览器配置',
  collector_provider: '采集服务',
  shop: '店铺',
  order: '订单',
  order_item: '订单明细',
  order_shipment: '订单发货',
  order_sync_task: '订单同步任务',
  order_exception: '订单异常',
  inventory_sync_task: '库存同步任务',
  inventory_sync_batch: '库存同步批次',
  customer_conversation: '客服会话',
  customer_reply_suggestion: '客服回复建议',
  customer_message_sync_task: '客服消息同步任务',
  worker_instance: '后台任务进程',
  task_center: '任务中心',
  task_alert: '任务告警',
  task_alert_notification: '任务告警通知',
  platform_app_settings: '平台应用设置',
  platform_publish_settings: '平台刊登设置',
  pricing: '定价规则',
};

/** 操作日志 · 操作动作中文映射（与后端 operationlog Action 一致） */
export const OPERATION_LOG_ACTION_LABEL: Record<string, string> = {
  login: '登录',
  'tenant.create': '创建租户',
  'tenant.rename': '租户改名',
  'tenant.disable': '停用租户',
  'tenant.enable': '启用租户',
  logout: '登出',
  register: '注册',
  email_code: '发送邮箱验证码',
  'email_code.send': '发送邮箱验证码',
  settings_update: '更新系统设置',
  'settings.alert_notify.update': '更新告警通知设置',
  'settings.pricing.update': '更新定价设置',
  test_ai: '测试 AI 连接',
  test_storage: '测试存储连接',
  test_email: '测试邮件发送',
  test_image: '测试图片服务',
  'product.create': '创建商品',
  'product.update': '更新商品',
  'product.delete': '删除商品',
  'product.sku.create': '创建商品规格',
  'product.sku.update': '更新商品规格',
  'product.sku.delete': '删除商品规格',
  'product.image.create': '添加商品图片',
  'product.image.update': '更新商品图片',
  'product.image.delete': '删除商品图片',
  'product.image.reorder': '调整商品图片顺序',
  'product.image.select_best_main': '自动选择最佳主图',
  'product.readiness.check': '检查商品发布就绪',
  'product.readiness.batch_check': '批量检查商品发布就绪',
  'product.publish.create': '创建商品刊登任务',
  'product.publish.running': '商品刊登执行中',
  'product.publish.success': '商品刊登成功',
  'product.publish.failed': '商品刊登失败',
  'product.publish.retry': '重试商品刊登',
  'ai.title_optimize.success': 'AI 标题优化成功',
  'ai.title_optimize.failed': 'AI 标题优化失败',
  'ai.title.apply': '应用 AI 标题',
  'ai.description_generate.success': 'AI 描述生成成功',
  'ai.description_generate.failed': 'AI 描述生成失败',
  'ai.description.apply': '应用 AI 描述',
  'ai.batch.create': '创建 AI 批量任务',
  'ai.batch.retry_failed': '重试 AI 批量失败项',
  'ai.batch.apply_results': '应用 AI 批量结果',
  'image.task.create': '创建 AI 图片任务',
  'image.task.success': 'AI 图片任务成功',
  'image.task.failed': 'AI 图片任务失败',
  'image.task.retry': '重试 AI 图片任务',
  'image.task.apply': '应用 AI 图片结果',
  'image.task.auto_retry_scheduled': 'AI 图片任务自动重试已计划',
  'image.task.auto_retry_enqueued': 'AI 图片任务自动重试已入队',
  'image.task.retry_exhausted': 'AI 图片任务重试耗尽',
  'image.task.lease_expired': 'AI 图片任务租约过期',
  'image.task_item.save': '保存 AI 图片任务项',
  'image.task_item.set_main': '设为 AI 图片主图',
  'collect.task.failed': '采集任务失败',
  'collect.task.retry': '重试采集任务',
  'collect.task.retry_exhausted': '采集任务重试耗尽',
  'collect.task.auto_retry_scheduled': '采集任务自动重试已计划',
  'collect.task.auto_retry_enqueued': '采集任务自动重试已入队',
  'collect.batch.retry_failed': '重试采集批次失败项',
  'collect.rule.create': '创建采集规则',
  'collect.rule.update': '更新采集规则',
  'collect.rule.delete': '删除采集规则',
  'collect.rule.test.success': '采集规则测试成功',
  'collect.rule.test.failed': '采集规则测试失败',
  'collect.browser_profile.create': '创建采集浏览器配置',
  'collect.browser_profile.disable': '禁用采集浏览器配置',
  'collect.browser_profile.open_login': '打开采集浏览器登录',
  'collect.browser_profile.check': '检查采集浏览器配置',
  'collect.pinduoduo.login_check': '检查拼多多登录状态',
  'collect.pinduoduo.open_login': '打开拼多多登录',
  'collect.pinduoduo.parse_warning': '拼多多采集解析警告',
  'collect.taobao_tmall.login_check': '检查淘宝/天猫登录状态',
  'collect.taobao_tmall.open_login': '打开淘宝/天猫采集浏览器',
  'collect.taobao_tmall.single': '淘宝/天猫单品采集',
  'collect.taobao_tmall.parse_warning': '淘宝/天猫采集解析警告',
  'collect.taobao_tmall.batch.create': '创建淘宝/天猫批量采集任务',
  'collect.taobao_tmall.batch.start': '淘宝/天猫批量任务开始',
  'collect.taobao_tmall.batch.complete': '淘宝/天猫批量任务完成',
  'collect.taobao_tmall.batch.task_success': '淘宝/天猫批量子任务成功',
  'collect.taobao_tmall.batch.task_failed': '淘宝/天猫批量子任务失败',
  'collect.taobao_tmall.batch.draft_created': '淘宝/天猫批量创建商品草稿',
  'collect.taobao_tmall.batch.skip_invalid_url': '淘宝/天猫批量跳过无效链接',
  'collect.taobao_tmall.batch.login_blocked': '淘宝/天猫批量登录状态异常',
  'collect.taobao_tmall.batch.verify_blocked': '淘宝/天猫批量安全验证异常',
  'collect.taobao_tmall.batch.pause_login': '淘宝/天猫批量因登录暂停',
  'collect.taobao_tmall.batch.pause_verify': '淘宝/天猫批量因验证暂停',
  'shop.create': '创建店铺',
  'shop.update': '更新店铺',
  'shop.delete': '删除店铺',
  'shop.auth.update': '更新店铺授权',
  'douyin.auth.start': '抖店发起授权',
  'douyin.auth.callback': '抖店授权回调',
  'douyin.auth.success': '抖店授权成功',
  'douyin.auth.failed': '抖店授权失败',
  'douyin.auth.refresh': '抖店刷新授权',
  'douyin.auth.revoke': '抖店解除授权',
  'douyin.shop.info.sync': '抖店店铺信息同步',
  'douyin.shop.connection.test': '抖店店铺连接测试',
  'douyin.category.sync.start': '抖店类目同步开始',
  'douyin.category.sync.success': '抖店类目同步成功',
  'douyin.category.sync.failed': '抖店类目同步失败',
  'douyin.category.attr.sync.start': '抖店属性同步开始',
  'douyin.category.attr.sync.success': '抖店属性同步成功',
  'douyin.category.attr.sync.failed': '抖店属性同步失败',
  'douyin.category.select': '抖店类目选择',
  'douyin.category.attr.update': '抖店属性更新',
  'douyin.mapping.build': '生成抖店刊登草稿',
  'douyin.mapping.save': '保存抖店刊登草稿',
  'douyin.mapping.validate': '校验抖店刊登草稿',
  'douyin.mapping.failed': '抖店刊登草稿校验失败',
  'douyin.image.upload.start': '抖店图片上传开始',
  'douyin.image.upload.success': '抖店图片上传成功',
  'douyin.image.upload.failed': '抖店图片上传失败',
  'douyin.image.upload.retry': '抖店图片上传重试',
  'douyin.image.storage.sync': '抖店图片同步到存储',
  'douyin.image.processed': '抖店图片处理',
  'douyin.order.sync.start': '抖店订单同步开始',
  'douyin.order.sync.success': '抖店订单同步成功',
  'douyin.order.sync.failed': '抖店订单同步失败',
  'douyin.order.sync.retry': '抖店订单同步重试',
  'douyin.inventory.sync.start': '抖店库存同步开始',
  'douyin.inventory.sync.success': '抖店库存同步成功',
  'douyin.inventory.sync.failed': '抖店库存同步失败',
  'douyin.inventory.sync.retry': '抖店库存同步重试',
  'douyin.inventory.sku.skipped': '抖店库存规格 跳过',
  'douyin.inventory.sku.failed': '抖店库存规格 失败',
  'douyin.product.draft.create.start': '抖店商品草稿创建开始',
  'douyin.product.draft.create.success': '抖店商品草稿创建成功',
  'douyin.product.draft.create.failed': '抖店商品草稿创建失败',
  'douyin.product.detail.sync.start': '抖店商品详情校准开始',
  'douyin.product.detail.sync.success': '抖店商品详情校准成功',
  'douyin.product.detail.sync.failed': '抖店商品详情校准失败',
  'douyin.sku.binding.matched': '抖店规格绑定匹配',
  'douyin.sku.binding.unmatched': '抖店规格绑定未匹配',
  'douyin.sku.binding.ambiguous': '抖店规格绑定待确认',
  'douyin.sku.binding.manual_bind': '抖店 SKU 手动绑定',
  'douyin.sku.binding.manual_unbind': '抖店 SKU 解除绑定',
  'douyin.sku.binding.recheck': '抖店规格绑定重新校准',
  'douyin.sku.binding.conflict': '抖店规格绑定冲突',
  'douyin.production.preflight': '抖店生产预检',
  'storage.public_access.test': '存储公网访问测试',
  'platform.settings.update': '更新平台应用设置',
  'platform.publish_settings.update': '更新平台刊登设置',
  'order.create': '创建订单',
  'order.update': '更新订单',
  'order.delete': '删除订单',
  'order.item.create': '创建订单明细',
  'order.item.update': '更新订单明细',
  'order.item.delete': '删除订单明细',
  'order.shipment.create': '创建发货记录',
  'order.shipment.update': '更新发货记录',
  'order.shipment.delete': '删除发货记录',
  'order.sync.create': '创建订单同步任务',
  'order.sync.running': '订单同步执行中',
  'order.sync.success': '订单同步成功',
  'order.sync.failed': '订单同步失败',
  'order.sync.retry': '重试订单同步',
  'order.sync.lease_expired': '订单同步租约过期',
  'order.sku_match.rebuild': '重建订单规格匹配',
  'order.sku_match.manual_bind': '手动绑定订单 SKU',
  'order.exception.handle': '处理订单异常',
  'order.exception.ignore': '忽略订单异常',
  'order.exception.unmark': '取消订单异常标记',
  'order.exception.bind_sku': '订单异常绑定 SKU',
  'order.exception.retry_deduct': '订单异常重试扣减',
  'order.exception.retry_inventory_sync': '订单异常重试库存同步',
  'inventory.sync.create': '创建库存同步任务',
  'inventory.sync.running': '库存同步执行中',
  'inventory.sync.success': '库存同步成功',
  'inventory.sync.failed': '库存同步失败',
  'inventory.sync.retry': '重试库存同步',
  'inventory.sync_batch.create': '创建库存同步批次',
  'inventory.sync_batch.retry_failed': '重试库存同步批次失败项',
  'inventory.stock.adjust': '调整库存',
  'inventory.stock_alert.update': '更新库存预警',
  'inventory.stock_alert.batch_update': '批量更新库存预警',
  'inventory.alert.sync_inventory': '同步库存预警',
  'inventory.order_deduct.sync_enqueue_failed': '订单扣减后同步入队失败',
  'inventory.order_restore.sync_enqueue_failed': '订单恢复后同步入队失败',
  'customer.conversation.create': '创建客服会话',
  'customer.conversation.update': '更新客服会话',
  'customer.conversation.close': '关闭客服会话',
  'customer.conversation.link_order': '客服会话关联订单',
  'customer.conversation.replied': '客服会话已回复',
  'customer.message.create': '创建客服消息',
  'customer.reply_generate.success': 'AI 客服回复生成成功',
  'customer.reply_generate.failed': 'AI 客服回复生成失败',
  'customer.reply_suggestion.edit': '编辑客服回复建议',
  'customer.reply_suggestion.accept': '采纳客服回复建议',
  'customer.reply_suggestion.discard': '丢弃客服回复建议',
  'customer.platform_message.send.success': '平台消息发送成功',
  'customer.platform_message.send.failed': '平台消息发送失败',
  'customer.message_sync.create': '创建客服消息同步任务',
  'customer.message_sync.running': '客服消息同步执行中',
  'customer.message_sync.success': '客服消息同步成功',
  'customer.message_sync.failed': '客服消息同步失败',
  'customer.message_sync.retry': '重试客服消息同步',
  'customer.message_sync.lease_expired': '客服消息同步租约过期',
  'worker.instance.start': '后台任务进程启动',
  'worker.instance.stop': '后台任务进程停止',
  'worker.task.lease_expired': '后台任务租约过期',
  'task_center.retry': '任务中心重试',
  'task_center.batch_retry': '任务中心批量重试',
  'task_center.ignore': '任务中心忽略',
  'task_center.handle': '任务中心标记处理',
  'task_center.unmark': '任务中心取消标记',
  'task_center.alert.scan': '扫描任务告警',
  'task_center.alert.generated': '生成任务告警',
  'task_center.alert.unmark': '取消任务告警',
  'task_center.alert.notify.manual': '手动发送任务告警通知',
  'task_center.alert.scan_worker.run': '任务告警扫描进程运行',
  'task_center.alert.scan_worker.failed': '任务告警扫描进程失败',
};

const SEGMENT_LABEL: Record<string, string> = {
  create: '创建',
  update: '更新',
  delete: '删除',
  success: '成功',
  failed: '失败',
  retry: '重试',
  running: '执行中',
  start: '启动',
  stop: '停止',
  apply: '应用',
  save: '保存',
  sync: '同步',
  login: '登录',
  logout: '登出',
  register: '注册',
  handle: '处理',
  ignore: '忽略',
  unmark: '取消标记',
  scan: '扫描',
  notify: '通知',
  adjust: '调整',
  reorder: '调整顺序',
  product: '商品',
  image: '图片',
  task: '任务',
  order: '订单',
  inventory: '库存',
  customer: '客服',
  worker: '后台任务',
  collect: '采集',
  shop: '店铺',
  ai: 'AI',
  batch: '批量',
  item: '明细',
  sku: '规格',
  exception: '异常',
  alert: '告警',
  instance: '进程',
  lease: '租约',
  expired: '过期',
  message: '消息',
  conversation: '会话',
  publish: '刊登',
  settings: '设置',
  platform: '平台',
  rule: '规则',
  profile: '配置',
  shipment: '发货',
  suggestion: '建议',
  generate: '生成',
  reply: '回复',
  deduct: '扣减',
  restore: '恢复',
  enqueue: '入队',
  scheduled: '已计划',
  enqueued: '已入队',
  exhausted: '耗尽',
  manual: '手动',
  bind: '绑定',
  rebuild: '重建',
  check: '检查',
  disable: '禁用',
  open: '打开',
  warning: '警告',
  select: '选择',
  best: '最佳',
  main: '主图',
  readiness: '发布就绪',
  title: '标题',
  description: '描述',
  optimize: '优化',
  results: '结果',
  stock: '库存',
  browser: '浏览器',
  pinduoduo: '拼多多',
  parse: '解析',
  auth: '授权',
  test: '测试',
  email: '邮件',
  code: '验证码',
  send: '发送',
  storage: '存储',
  pricing: '定价',
  center: '中心',
  generated: '生成',
  scan_worker: '扫描进程',
  task_item: '任务项',
  set: '设置',
  auto: '自动',
  retry_failed: '重试失败项',
  sync_batch: '同步批次',
  sync_inventory: '同步库存',
  stock_alert: '库存预警',
  batch_update: '批量更新',
  batch_check: '批量检查',
  batch_retry: '批量重试',
  order_deduct: '订单扣减',
  order_restore: '订单恢复',
  sync_enqueue_failed: '同步入队失败',
  message_sync: '消息同步',
  reply_generate: '回复生成',
  reply_suggestion: '回复建议',
  platform_message: '平台消息',
  sku_match: '规格匹配',
  manual_bind: '手动绑定',
  retry_deduct: '重试扣减',
  retry_inventory_sync: '重试库存同步',
  retry_exhausted: '重试耗尽',
  auto_retry_scheduled: '自动重试已计划',
  auto_retry_enqueued: '自动重试已入队',
  lease_expired: '租约过期',
  link_order: '关联订单',
  select_best_main: '选择最佳主图',
  alert_notify: '告警通知',
  publish_settings: '刊登设置',
  app_settings: '应用设置',
};

function humanizeDottedKey(key: string): string {
  const normalized = key.replace(/_/g, '.');
  const parts = normalized.split('.').filter(Boolean);
  if (parts.length === 0) return key;
  const translated = parts.map((part) => {
    if (SEGMENT_LABEL[part]) return SEGMENT_LABEL[part];
    const chunks = part.split('_').filter(Boolean);
    if (chunks.length <= 1) return part;
    return chunks.map((c) => SEGMENT_LABEL[c] || c).join('');
  });
  return translated.join(' · ');
}

export function operationLogResourceLabel(resource?: string): string {
  const k = (resource || '').trim();
  if (!k) return '—';
  return OPERATION_LOG_RESOURCE_LABEL[k] || humanizeDottedKey(k);
}

export function operationLogActionLabel(action?: string): string {
  const k = (action || '').trim();
  if (!k) return '—';
  return OPERATION_LOG_ACTION_LABEL[k] || humanizeDottedKey(k);
}

export const OPERATION_LOG_RESOURCE_OPTIONS = Object.entries(OPERATION_LOG_RESOURCE_LABEL).map(
  ([value, label]) => ({ value, label }),
);

export const OPERATION_LOG_ACTION_OPTIONS = Object.entries(OPERATION_LOG_ACTION_LABEL).map(
  ([value, label]) => ({ value, label }),
);
